### ISSUE TITLE
Add support for "UserMulti" field

### ISSUE THREAD

**Issue by ewrogers** [jasonrollins/shareplum#10]
The current version of the library cannot publish to lists with `UserMulti` field types. It will error out with `"Invalid look-up value"`.

It's a relatively easy fix, just needs to be added to the `if/elif` block at line 303 **and** 331.

    - elif field_type == 'User':
    + elif field_type in ('User', 'UserMulti'):

**Comment by jasonrollins** [comment]
Looks good.  Thanks!

**Comment by jasonrollins** [comment]
It's now committed.  Thanks for the input.
