### ISSUE TITLE
'Site' object has no attribute 'Folder'

### ISSUE THREAD

**Issue by azharmajeed** [jasonrollins/shareplum#100]
Hi,

I am trying to download a xlsx file in a sharepoint folder. When I run this code
```
authcookie = Office365(spDomain, username='******', password='*****').GetCookies()
site = Site(spsite, Version.v2016, authcookie=authcookie)
folder = site.Folder('Shared Documents/General/Sub Folder/')
```

I get the error saying -
```
AttributeError: 'Site' object has no attribute 'Folder'
```

I dont get what I am doing wrong. I am using version "0.5.1". Could you please help me figure out the issue or find a work around to download a file. Appreciate any help.

**Comment by azharmajeed** [comment]
I found the issue, when I was importing ---
```
from shareplum import Site
from shareplum import Office365
```

it was importing just one script called shareplum.py(which had the methods called Site but not Folder class) instead from the parent library folder called shareplum. So fixed it by using import site and office365 with lowercase.
Not sure if others have the same issue though.

**Comment by isaacnorman82** [comment]
@azharmajeed I do this:

```
from shareplum import Office365, Site
from shareplum.site import Version

authcookie = Office365(my_host, username=my_username, password=my_pw).GetCookies()
site = Site(site_url, version=Version.v365, authcookie=authcookie)
folder = site.Folder(folder_path)
```

The only difference from what you had was i'm using Version.v365, but I think under the hood shareplum treats these the same - at least at a glance of the code it does.

You mention shareplum.py - how have you installed it, in your environment using pip?

**Comment by azharmajeed** [comment]
![image](https://user-images.githubusercontent.com/52348318/81729533-c1cc5880-94a9-11ea-8536-02d74e27da54.png)

@isaacnorman82 
Yes I used pip install. I think the shareplum.py is from the older the versions, not sure how it got there. I guess removing that file also should take care of the issue.

**Comment by isaacnorman82** [comment]
I would uninstall shareplum, verify it's gone and reinstall.
