### ISSUE TITLE
Office365 connection spontaneously broke

### ISSUE THREAD

**Issue by jarichardsonccbf** [jasonrollins/shareplum#101]
Good morning,

I had been using the following code daily for the past month or so to pull a SP list and connect to another data source

`from shareplum import Site`
`from shareplum import Office365`
`import pandas as pd`

`authcookie = Office365('https://COMPANY.sharepoint.com',` `username='SharePointAdmin@COMPANY.com', password='ADMINPW').GetCookies()`
`. . .`

However it seems to have spontaneously broken and am now getting the error:

`Exception: Check username/password and rootsite`

I don't have enough Python or sharepoint knowledge to understand whose end this error is on. Seems to be an authentication issue but it was working fine and our SP guy says nothing has changed.

**Comment by jasonrollins** [comment]
Do you know if you changed versions of Shareplum?

**Comment by jarichardsonccbf** [comment]
No sir, haven't touched anything in that regard.

**Comment by isaacnorman82** [comment]
Can you find the installed shareplum you're using - and report the version in version.py?

Alternatively, without touching your current environment you could create a new virtual env and install the latest shareplum:

```
python -m venv env
windows:  env/Scripts/Activate.bat
unix: source env/bin/activate
pip install shareplum==0.5.1
```

Then see if your script works.

**Comment by jarichardsonccbf** [comment]
So, this actually appears to be an internal issue. Just got word from a colleague who pulls a SP list into Tableau that their connection there is failing too. Someone touched something somewhere. Will reopen if that's not the case. Appreciate your help!
