### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by rjwiii** [jasonrollins/shareplum#11]
Hello,

Does this library have a "verify_ssl=False" or a "verify=False" option or a method to pass a cert?

Thanks,

rjwiii

**Comment by rjwiii** [comment]
Never mind ... :) Found it reading the code ...

Thanks,

rjwiii

**Comment by jasonrollins** [comment]
Would you mind suggesting an improvement to the documentation?

**Comment by shoother813** [comment]
What's the option to disable the SSL check?
