### ISSUE TITLE
How do you add new items to list?

### ISSUE THREAD

**Issue by rakeshtinde** [jasonrollins/shareplum#124]
I am adding new items to a LookUp type column in a list and I am unable to do so.

I am getting this error: {'1,New': ('0x80020005',
  'The operation failed because an unexpected error occurred. (Result Code: 0x80020005)')}

Thanks,

**Comment by rakeshtinde** [comment]
never mind solved it !

**Comment by kannes** [comment]
How did you solve it though? Please share the reason with others so they can benefit from your knowledge if they encounter the same problem.
