### ISSUE TITLE
Apostrophes in folder/file names break Folder methods

### ISSUE THREAD

**Issue by jmriebold** [jasonrollins/shareplum#130]
When Sharepoint folders or files contain apostrophes, the Sharepoint API will return a 400 error.

For example:

```python
folder = site.Folder("Shared Documents/John's Stuff")
for file in folder.files:
   ...
```

will result in:

```python
shareplum.errors.ShareplumRequestError: Shareplum HTTP Get Failed : 400 Client Error: Bad Request for url: https://some-site.sharepoint.com/sites/example/_api/web/GetFolderByServerRelativeUrl('Shared%20Documents/John's%20Stuff')/files
```

See this [StackExchange post](https://sharepoint.stackexchange.com/questions/154590/getfilebyserverrelativeurl-fails-when-the-filename-contains-a-quote) for more details.

**Comment by Thomas-td** [comment]
I believe it breaks again when using `folder.folders`:
```
folder = site.Folder("Shared Documents/John's Stuff")
for file in folder.files:
   ...
```

**Comment by Thomas-td** [comment]
Changing the single apostrophe for a double apostrophe doesn't fix it for me, I am able to access the folders in the folder with the apostrophe, but it also creates a new folder with two apostrophes:

First I only have folder "Thomas' files"
After running: `folder = site.Folder("Shared Documents/Thomas'' files")`
I have "Thomas' files" and "Thomas'' files"

How do I fix that?
