### ISSUE TITLE
How secure my data when using Shareplum libraray?

### ISSUE THREAD

**Issue by msjahid** [jasonrollins/shareplum#143]
I want to ensure my Data security. Because it is third party library. I want to use this library for my company purposes. Anyone share valid information for this criteria.

**Comment by jasonrollins** [comment]
This code relies on the requests library and uses ssl.  As far as I know, it is as secure as using a web browser while using SharePoint.  The code is relatively simple so you can look through it to see that nothing sketching is going on.  Make sure to follow best practices like not including usernames or passwords in your code.
