### ISSUE TITLE
Created Field

### ISSUE THREAD

**Issue by Sneezeplease** [jasonrollins/shareplum#15]
I really like the way shareplum is setup. I am having one issue though in a sharepoint 2010 test env I created. 

The created field will have some characters before the date only when implicitly selecting the field or when using the query function with GetListItems. If I download all the data and don't specifically ask for created, I get a proper datetime. Any idea what could be causing this?

GetListItems(fields=['Created'])    -- Returns the following

[{'Created': '1;#2017-10-04 11:56:20'}, {'Created': '2;#2017-10-04 12:43:46'}, {'Created': '3;#2017-10-04 14:25:42'}, {'Created': '4;#2017-10-04 14:27:27'}, {'Created': '5;#2017-10-04 14:43:45'}, {'Created': '6;#2017-10-04 14:45:07'}]

**Comment by jasonrollins** [comment]
I've seen this myself.  I'm not sure what causes it.  Are you using Python 2 or 3?  Do the numbers exist in the raw response from Sharepoint?  Have you seen it with Sharepoint 2013?

**Comment by Sneezeplease** [comment]
I've tested it with Python 2 and 3, but the same thing happens. The server I plan to use this script on is 2010, so that's the test env I setup. If I have some time I will create another VM and install 2013 to test, it might be specific to the version. When I ran the script on the actual server, I'm getting the same result. 

I'm not sure about the raw response from Sharepoint, but I know if I read all the fields, it outputs correctly. 

As a workaround I just split the results for Created and Modified at ';#'

**Comment by larrys** [comment]
I might have a fix for this. Can you check https://github.com/larrys/shareplum/commit/03cc0e9990e15a5a6c1e9feacabc19e8f4e000f9 and apply that change locally, and let me know, if it fixes it, I'll get a proper pull request in.

**Comment by Sneezeplease** [comment]
larrys,

I will test this later tonight and report back. I imagine this will correct the issue.

**Comment by Sneezeplease** [comment]
I'm sad to say this did not the fix the issue. It appears that it is never reaching that else if.

I printed the field_type in the scenario: GetListItems(fields=['Created']) and it shows the type as 'Lookup'.
In the scenario: GetListItems('All Items') the type is as expected, 'DateTime'. 

I'm wondering if 'Folder Child Count' is the culprit. The field type for this is Lookup.

GetListItems(fields=['Folder Child Count']) 
[{'Folder Child Count': '1;#0'}, {'Folder Child Count': '2;#0'}, {'Folder Child Count': '3;#0'}, {'Folder Child Count': '4;#0'}, {'Folder Child Count': '5;#0'}, {'Folder Child Count': '6;#0'}, {'Folder Child Count': '7;#0'}]

**Comment by jasonrollins** [comment]
I've updated the code that may fix this.
