### ISSUE TITLE
Problems passing a User Field

### ISSUE THREAD

**Issue by Nireck19** [jasonrollins/shareplum#16]
Hello

I am having a problem when passing a user field into the sharepoint list.  It says that Sharepoint cannot change it into internal data and  then cuts the whole process.

is there something I am doing wrong I have ran out of options, I tried to pass user name, ID  even email but is not working.

**Comment by jasonrollins** [comment]
Can you tell me which version of Python you are using?  Which Sharepoint version and an example of the code that gives the error?

**Comment by Nireck19** [comment]
Python 3.X

`list =  site.List('Awards Scorecard 2017-2018')

df = pd.read_excel('Awards.xlsx')
df = df.fillna(value="")
upload_data = df.to_dict('records')
print(upload_data)

list.UpdateListItems(data=upload_data,kind='New')`

the problem is that on the Debugger it Says that the User field cannot handle the Data conversion.

**Comment by jasonrollins** [comment]
Does your data have a field called "User" that is supposed to match with
SharePoint users on your site?  If you remove the "User" column do you get
the same issue?

**Comment by Nireck19** [comment]
I am currently working on that.  I have asked to have the column removed and see if that fixes the issue. i will let you know how unfolds.

**Comment by jasonrollins** [comment]
Thanks, you can check the "Type" for the column in question in Sharepoint
to see if it's a "User" type.  It may be that the User you are trying to
add doesn't exist.  Can you give me a copy of the output for the error?

**Comment by Nireck19** [comment]
I am guessing my problem is somewhere else when I try to upload a line I get this error

 File "C:/Users//PycharmProjects/untitled2/Sharepoint2.py", line 16, in <module>
    list.UpdateListItems(data=upload_data,kind='New')
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\shareplum\shareplum.py", line 545, in UpdateListItems
    self._convert_to_internal(data)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\shareplum\shareplum.py", line 271, in _convert_to_internal
    _dict[self._disp_cols[key]['name']] = self._sp_type(key, _dict.pop(key))
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\shareplum\shareplum.py", line 327, in _sp_type
    return self.users['py'][value]
KeyError: ''

**Comment by Nireck19** [comment]
I realized which my mistake was. If I pass a Blank string into the Modified/Created by Column Sharepoint throws an error so I dropped them  and now it  works. My Bad man this should not have been an issue in the first place

**Comment by jasonrollins** [comment]
No worries.  Most of the issues with SharePlum lately have been about that
User field.  I was contemplating nixing the whole thing.  I'm glad you got
it working.

**Comment by Nireck19** [comment]
Yup at least a note will be in order so everyone can work thinks around
