### ISSUE TITLE
Error authenticating against Office 365

### ISSUE THREAD

**Issue by nattafahhm** [jasonrollins/shareplum#180]
using this

from shareplum import Site
from shareplum import Office365

authcookie = Office365('https://abc.sharepoint.com', username='username@abc.com', password='password').GetCookies()
site = Site('https://abc.sharepoint.com/sites/MySharePointSite/', authcookie=authcookie)
sp_list = site.List('list name')
data = sp_list.GetListItems('All Items', row_limit=200)

**Exception: ('Error authenticating against Office 365. Error from Office 365:', "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access ''.")**

**Comment by nattafahhm** [comment]
I solved it

**Comment by JuanPabloCarrionSalazar** [comment]
How did you solve it? Please

**Comment by Dhafer145** [comment]
could you please tell us how you did solve it?

**Comment by JuanPabloCarrionSalazar** [comment]
I used another approach, i connected an excel file to the same sharepoint list so i didn't have problems with the MFA
