### ISSUE TITLE
Can't use OrderBy without Where

### ISSUE THREAD

**Issue by atomheart** [jasonrollins/shareplum#19]
It seems that it is impossible use of OrderBy query without Where query because you have next IF-condition:

```python
        # Add query
        if query:
            where = etree.Element('Where')

            parents = []
            parents.append(where)
            # HERE you try to get Where without checking:
            for i, field in enumerate(query['Where']):
```

Is this right?

**Comment by jasonrollins** [comment]
Yes, It's been a while but I believe that SharePoint requires it.

**Comment by atomheart** [comment]
Blocks Where and OrderBy are not linked each other, so I think the may work separately.

Here are their descriptions:
- Where element: https://msdn.microsoft.com/ru-ru/library/office/ms414805.aspx
- OrderBy element: https://msdn.microsoft.com/ru-ru/library/office/ms467378.aspx

Both of them may be omitted.

**Comment by atomheart** [comment]
If I'm wrong, then you need to fix documantation: http://shareplum.readthedocs.io/en/latest/queries.html
Because in your examples OrderBy and GroupBy are single conditions.

**Comment by dgutman** [comment]
was just trying this , and yeah the documentation suggests OrderBy can be used without a where.. but it throws an exception..

**Comment by jasonrollins** [comment]
Should be fixed now.  I thought I was automatically adding the 'Where', but I wasn't.  It should no longer be required.
