### ISSUE TITLE
unable to authenticate with O365 SharePoint

### ISSUE THREAD

**Issue by jayID45** [jasonrollins/shareplum#22]
I'm guessing NTLM is the only authentication method currently supported. Are there any plans to make shareplum work with Office 365 SharePoint?

**Comment by atomheart** [comment]
I'm working both with Basic and NTLM authorizations. There is no constraints. But I'm working with "local" SharePoint (local network). Show what error you recieved during connection.

**Comment by jayID45** [comment]
I'm receiving a token request failed message. It appears to be failing on this line of code:
token = root.find(".//wsse:BinarySecurityToken", ns).text

**Comment by atomheart** [comment]
Please show your code and error you recieved.

**Comment by jayID45** [comment]
I was able to get my code working. In the end, I used your code to read lists from our on-prem sharepoint, and the link below to help me connect to O365 using a registered app and Azure security tokens. I updated the SharePoint online list using json and the Microsoft Graph REST framework. 
https://docs.microsoft.com/en-us/outlook/rest/python-tutorial. 

I really appreciate your project. It was by far much easier to use than any other examples I've tried. All the best!

**Comment by lanreogun** [comment]
Are there any future plans to support connection to Ofiice 365?

**Comment by jasonrollins** [comment]
Yes, I would say so.  I haven't had the time to work on it, but would gladly accept a pull request for such feature.

**Comment by fatfingers23** [comment]
I just created a Pull Request for this feature, hopefully this will work for everyone!

**Comment by jasonrollins** [comment]
fatfingers23 has a working solution.  I've merged that change and fixed and issue with the Created Date value that get returned and release those fixes as 0.2.0.
