### ISSUE TITLE
GetListItems()  doesnt return all rows

### ISSUE THREAD

**Issue by jordan-carson** [jasonrollins/shareplum#28]
GetListItems() only returns a subset of the entire dataset and not all rows

**Comment by jasonrollins** [comment]
GetListItems() without any arguments pulls the default list view.  If that view filters any data you won't see it.  You need to pass in view that has the data or send your own filter that includes all of the data.

**Comment by gwsampso** [comment]
I think I'm experiencing a similar issue... but not 100% sure.

Could you please help @jasonrollins 

In my browser the url returns the following  /_api/web/lists/GetByTitle('Products')/items?&$filter=ID 7271

        <d:Id m:type="Edm.Int32">7271</d:Id
        <d:ApprovalStatus>Accepted</d:ApprovalStatus>
        <d:ConfidentialAgreementStartDate m:null="true"/>
        <d:ConfidentialAgreementEndDate m:null="true"/>
        <d:IsInConfidentialAgreement m:type="Edm.Boolean">false</d:IsInConfidentialAgreement>
        <d:SectorAttributesId m:type="Collection(Edm.Int32)">
          <d:element>29</d:element>
          <d:element>104</d:element>
          <d:element>43</d:element>
          <d:element>34</d:element>
          <d:element>46</d:element>
          <d:element>20</d:element>
          <d:element>32</d:element>
          <d:element>36</d:element>
        </d:SectorAttributesId>

Shareplums GetListItems()  returns everything but SectorAttributesID....

Should SectorAttributeID get picked up?

Or is this list of list setup not a feature?

**Comment by jasonrollins** [comment]
SharePlum uses SOAP and not REST.  I'm a bit unfamiliar with the REST
features of SharePoint.  What is the use case here?
