### ISSUE TITLE
v0.1.1 NameError: global name 'new_list' is not defined

### ISSUE THREAD

**Issue by kaz399** [jasonrollins/shareplum#3]
I tried v0.1.1 and got the following error:

```
  File "D:\Python27\lib\site-packages\shareplum\shareplum.py", line 367, in GetListItems
    viewfields = [x for x in new_list._sp_cols]
NameError: global name 'new_list' is not defined
```

Would you please fix it?

**Comment by jasonrollins** [comment]
Whoops.  Should be 'self'.  Not 'new_list'.

**Comment by TE-0000109096** [comment]
Thank you.
It works fine!

**Comment by kaz399** [comment]
Thank you.
It works fine!

**Comment by jasonrollins** [comment]
Great.  Thanks for your help.  When I add in the UpdateList functionality I'll be able to build some unit tests to catch these types of issues.
