### ISSUE TITLE
Unable to update items with Hyperlink or Picture column type

### ISSUE THREAD

**Issue by namannik** [jasonrollins/shareplum#33]
I have a list in which one column's type is "Hyperlink or Picture".  When calling `UpdateListItems`, if the data contains a value for this column, no data is written for the row and all following rows.

**Comment by jasonrollins** [comment]
This code works for me.  Can you check it?

my_data = data=[{'Title': 'Another Row!', 'Cool Hyper Link': 'http://www.contoso.com, This Works'}]
cool_list.UpdateListItems(data=my_data, kind='New')
