### ISSUE TITLE
Reach subfolders

### ISSUE THREAD

**Issue by MarkWallbang** [jasonrollins/shareplum#38]
Hi,

is it possible to access subfolders with this library? Because I have a library where there are multiple folders under which a list is located that I want to fetch. However I somehow cannot query down into the folders. 
When I try to fetch the lists the only thing I get back is the folders. 

`
site = Site('htttps://sharepoint.mycompany.com/content/sitename',auth=cred)
list=site.List(listname)
list.GetListItems('All Documents')
`

This gives me all the names of the folders (listname is the name of the library). When I try to put it like

`
site=Site('htttps://sharepoint.mycompany.com/content/sitename/listname',auth=cred)
list=site.List(foldername)
`
it gives me an error. Same goes when I try to put the folder in the listname like

`
site=Site('htttps://sharepoint.mycompany.com/content/sitename',auth=cred)
list=site.List(foldername/listname)`

Can I achieve what I want with this package? Thank you!

**Comment by jasonrollins** [comment]
Can you tell me what version of SharePoint you're using so I can try to
replicate it?  Is this an actual list or is it a Document Library?

**Comment by MarkWallbang** [comment]
Hi,

it is a SharePoint 2010 instance running on-premise. And it is a Document Library. Nonetheless I can get the names of all the folders on first level just below the Document Library. I would expect that you can also reach subfolders somehow. 
Thank you for your fast response!

**Comment by nyleenho** [comment]
I have the same question:
How to get documents from sub-folders of a document-library in an Office-365 sharepoint?

**Comment by MarkWallbang** [comment]
Hi,
I realized that it is not possible with shareplum and hence changed the code of the library a little bit. I can give you the code later when I get home if you like.

**Comment by nyleenho** [comment]
I copied the file from the pull-request on github
(https://raw.githubusercontent.com/jasonrollins/shareplum/0ec338cef675def3de24cf4e253384fc35146cdb/shareplum/shareplum.py)
to my local installation (~/.local/lib/python3.4/site-packages/shareplum/shareplum.py)
and it works.
Thanks a lot!

**Comment by jasonrollins** [comment]
@nyleenho Yes if you could.  I've done a bit a research on this and I can't figure out the SOAP commands to do it.  If you could share that with me, I would appreciate it.

**Comment by nyleenho** [comment]
I don't know what I should share.
I just used the file shareplum.py I found on the pull-request on github:
https://github.com/jasonrollins/shareplum/pull/34
and that works fine.

**Comment by jasonrollins** [comment]
@nyleenho Does it work on SharePoint 2010?

**Comment by nyleenho** [comment]
I don't know, I'm only using Office-365.

**Comment by jasonrollins** [comment]
I've only been able to implement Files and Folder access to SharePoint 2013+ by using the REST API.  I haven't been able to figure out how to do it with SOAP.
