### ISSUE TITLE
Support for document library uploads

### ISSUE THREAD

**Issue by nick-bull** [jasonrollins/shareplum#4]
One massive oversight of all these SharePoint libraries (there are several here on GitHub written in Python that I could find) is a lack of document library support. 

While lists are easier to use, it's almost always the case that directory-like uploads should be in a document library. Please include supporting methods for this use case, and you'd be the first (or, at least, the first I know of) to include such functionality.

**Comment by jasonrollins** [comment]
Thanks for the info!  I definitely plan on implementing some of these
features.

**Comment by jasonrollins** [comment]
This should be implemented in SharePlum v0.4.2.  You do need to have SharePoint 2013 and greater to use it though.
