### ISSUE TITLE
Fix "Invalid STS request" inside shareplum.Office365?

### ISSUE THREAD

**Issue by ffunenga** [jasonrollins/shareplum#45]
I was getting the "Invalid STS request" error when running `shareplum.Office365(...)`. It turns out that my username & password have invalid XML characters that make shareplum fail.

I found [a way to fix it](https://allthatjs.com/2012/03/28/remote-authentication-in-sharepoint-online/#comment-3192) by escaping the username and the password before running `shareplum.Office365(...)`:

```python
from shareplum import Office365
from xml.sax.saxutils import escape

authcookie = Office365(server_url, username=escape(username), password=escape(password)).GetCookies()
```

Maybe, this could be done inside the `shareplum.Office365(...)` class by default?

**Comment by jasonrollins** [comment]
Thanks!  I'll look into it.  Can you tell me what invalid XML characters
you were using?

**Comment by jasonrollins** [comment]
Implemented.  Thanks.
