### ISSUE TITLE
UpdateList(data=newData, kind=“New”) does not add all fields that I pass in

### ISSUE THREAD

**Issue by mmolinahn** [jasonrollins/shareplum#46]
I have a new row to add:

newData =[{‘Title’: ‘title’, ‘otherfield’: ‘stuff’, ‘Name’: ‘name’}]

Then I run:
SpList.UpdateList(data=newData, kind=“New”)
The row is added, but the field Name is left blank even though I provided a value for it. The same happens when I try to update the Name field.

Is name some sort of key word and that’s why it does not work?
 The type of that field is Single line of text

**Comment by jasonrollins** [comment]
I'm not sure.  That looks like that should work.  Are you sure the field
isn't protected in any way?  The column name should be the displayed name
that you see in a web browser.  Does it show up as "Name" exactly in your
web browser?  If 'otherfield' is working I would think that 'Name' should
be.

Thanks,
Jason
