### ISSUE TITLE
Column datetime in sharepoint is get only date

### ISSUE THREAD

**Issue by esousaa** [jasonrollins/shareplum#47]
My list has 2 columns with datetime format but when I get the data in python, the format is change to only date.

How can I get the both date and time?

Thanks

![erro](https://user-images.githubusercontent.com/37678848/61155111-754d7080-a4c6-11e9-88a2-b75dca66eb7e.png)

**Comment by jasonrollins** [comment]
This is fixed in the current version on Github.  Sorry about that.  It's in
the "_python_type" function. You can change it in your version or get the
latest version on github.

Thanks,
Jason

**Comment by esousaa** [comment]
Thanks.

I upgrade the version and resolve my problem.
