### ISSUE TITLE
Failed connect Sharepoint 365

### ISSUE THREAD

**Issue by esousaa** [jasonrollins/shareplum#48]
Hi dears,

I try connect in our sharepoint 365 and the followin error occurred:

c:\program files\python\lib\site-packages\shareplum\shareplum.py in GetCookies(self)
     73         and uses it as Authentication for the rest of the calls
     74         """
---> 75         sectoken = self.GetSecurityToken(self.Username, self.Password)
     76         url = self.share_point_site+ '/_forms/default.aspx?wa=wsignin1.0'
     77         response = requests.post(url, data=sectoken)

c:\program files\python\lib\site-packages\shareplum\shareplum.py in GetSecurityToken(self, username, password)
     66             return token.text
     67         else:
---> 68             raise Exception('Check username/password and rootsite')
     69 
     70     def GetCookies(self):

Exception: Check username/password and rootsite

I used the follows commands to try connect:

authcookie = Office365('https://onsbr.sharepoint.com', username='', password='').GetCookies()
site = Site('site', authcookie=authcookie)

I need configure something in my sharepoint ?

Thanks

**Comment by jasonrollins** [comment]
Could this be related to [Issue 32](https://github.com/jasonrollins/shareplum/issues/32)? Is this an personal online SharePoint site or a business site with SSO?

**Comment by esousaa** [comment]
It's business site with SSO

**Comment by jasonrollins** [comment]
I believe this is now fixed in v0.4.2.
