### ISSUE TITLE
`UpdateListItems` modifies input fields list

### ISSUE THREAD

**Issue by VimanyuAgg** [jasonrollins/shareplum#50]
I found that the function `List.UpdateListItems()` modifies the dictionary item in the list as it calls `self._convert_to_internal()` on the data. 

I believe that this should be explicitly mentioned in the documentation or the function should be modified to create a deep_copy of the data.

If the latter option works, please let me know and I'll submit a PR :)

**Comment by jasonrollins** [comment]
Yes, this was an early design decision to modify the data right before sending it.  I didn't want to create a copy at the time.  Do you have a use case where this causes an issue?

**Comment by jasonrollins** [comment]
I'm closing this issue as it's a known design decision.  I can modify the way it works if it is causing real world problems.
