### ISSUE TITLE
No module named 'shareplum'

### ISSUE THREAD

**Issue by BernydotJar** [jasonrollins/shareplum#54]
File "C:\Users\Eduardo Sacahui\Documents\sharepoint_upload.py", line 2, in <module>
    from shareplum import Site

(<class 'ModuleNotFoundError'>, ModuleNotFoundError(...areplum'"), <traceback object at...0A02A0CC8>)

**Comment by jasonrollins** [comment]
Did you install it already? pip install shareplum

**Comment by BernydotJar** [comment]
Thank you for your time, and ... Yes sir, via CMD and nothing(had to use pip install SharePlum --user), I uninstalled python it and then flagged the PATH options, IDK I thought that was the problem and nothing, I tried to run it from cmd and from VS code and it says


Traceback (most recent call last):
  File "C:\Users\Eduardo Sacahui\Documents\sharepoint_upload.py", line 2, in <module>
    from shareplum import Site
ModuleNotFoundError: No module named 'shareplum'


I looked over the internet and nothing, my import is like this:

import requests 

from shareplum import Office365
from config import config

**Comment by jasonrollins** [comment]
Sorry.  Were you able to resolve your issue?
