### ISSUE TITLE
Incorrect Mapping of return XML from GetList: Resulting into KeyError['Title']

### ISSUE THREAD

**Issue by iskai001** [jasonrollins/shareplum#56]
When the REST call returns a DocumentLibrary with Validation and ValidationResults, it is stored on index[0] and index[1] correspondingly. 

Object: _List
Method: GetList
          
           for row in _list[0].getchildren():
                self.fields.append({key: value for (key, value) in row.items()})

            for setting in _list[1].getchildren():
                self.regional_settings[
                    setting.tag.strip('{http://schemas.microsoft.com/sharepoint/soap/}')] = setting.text

            for setting in _list[2].getchildren():
                self.server_settings[
                    setting.tag.strip('{http://schemas.microsoft.com/sharepoint/soap/}')] = setting.text

Suggestions:
getTagIdx = lambda l, t: [idx for idx, val in enumerate(l) if val and val.tag.find(t) > 0].pop()
fieldIdx = getTagIdx(_list, 'Fields)
regionalIdx = getTagIdx(_list, 'RegionalSettings')
serverIdx = getTagIdx(_list, 'ServerSettings')

replace the blind use of index number with the expected index coming from the function

**Comment by jasonrollins** [comment]
If this is specifically for the REST api, I'd like to move this issue to SharePlum2.  Thanks.

**Comment by jasonrollins** [comment]
I'm not sure what code you are running here.
