### ISSUE TITLE
Out of Memory Errors on Server

### ISSUE THREAD

**Issue by bhazard** [jasonrollins/shareplum#57]
Hi Folks - I had issues related to out of server memory for GetListItems calls that returned tons of results (server would return either 500 error or would return 200 status code with an "error page" that indicated out of memory).  I was able to fix this by implement paging.  I have code that does this, would it be helpful to pull-request?  Just asking as SOAP is soo old for SharePoint and I'm not sure how many folks are on the ancient pre-REST versions.  We're on SP 2007.  LMK if helpful and I can post what we did.

**Comment by jasonrollins** [comment]
I'm interested in improving this version of the library for 2007 to 2013 version of SharePoint.  I'd appreciate any PRs you have that would help.  Thanks in advance.

**Comment by jasonrollins** [comment]
SharePoint has a limitation of 5000 rows.  That could be your issue.  This can not be resolved by SharePlum.  You will have to use Views or Indexing to get around this.
