### ISSUE TITLE
Parsing Errors

### ISSUE THREAD

**Issue by bhazard** [jasonrollins/shareplum#58]
We had some issues with parsing 2007 SP responses.  The fix we used was to supply a "Recover=True" to the XMLParser constructor in sharepoint.py
            `envelope = etree.fromstring(response.text.encode('utf-8'), parser=etree.XMLParser(huge_tree=self.huge_tree, recover=True))`

I am posting here in case it helps others who are as far behind our SP upgrades as we are.  Happy to PR if helpful.

Pls LMK if I should create a PR.

**Comment by jasonrollins** [comment]
Does this change break anything for SharePoint 2010 or 2013?  I'd like to add it to SharePlum if it helps for older versions.

**Comment by jasonrollins** [comment]
Thanks.  I added it.
