### ISSUE TITLE
Not able to Delete a file on my list

### ISSUE THREAD

**Issue by mayankminawat** [jasonrollins/shareplum#59]
I'm trying to delete a file that's located on my sharepoint site list. I've tried all possible solutions and can't find an example online on how to format my code. File that I want to delete has an ID of 85, its printing the ID's correctly but gives me below error. Any help is greatly appreciated.
Code:

        auth = get_sharepoint_auth() 
        site = Site(SHAREPOINT_API, auth=auth)
        
        sp_list = site.List('My List')
        
        data = sp_list.GetListItems()
        for x in data:
            print(x['ID'])
            if x['ID']=='85':
                y=sp_list.UpdateListItems(['85'],'Delete')
                print(y)

Result-set:
85
{'1,Delete': ('0x81020030', 'Invalid file name.\n\nThe file name you specified could not be used.  It may be the name of an existing file or directory, or you may not have permission to access the file.')}
89
88
87
86
83
82
81

**Comment by jasonrollins** [comment]
Files are a bit of mystery for me with the SOAP architecture (what SharePlum uses).  I've spent some time with the Microsoft docs and I've never been able to successfully deal with files using SOAP commands.  If you have SharePoint 2013 and newer I would suggesting looking into the REST api.  SOAP is no longer officially supported, but it is the only option for SharePoint severs older than 2013.

**Comment by jasonrollins** [comment]
I'm closing this issue since it relates to Files.  I'm working on supporting Files in SharePlum2.
