### ISSUE TITLE
Cannot connect to the Sharepoint portal

### ISSUE THREAD

**Issue by Mark531** [jasonrollins/shareplum#62]
Hello,

I've tried to connect to my intranet Sharepoint portal with shareplum to no avail.

This code:
> authcookie = Office365('https://mycompany.sharepoint.com', username='my_user_name@mycompany.com', password='my_password').GetCookies()

returns:

> Exception: Check username/password and rootsite

Though, the identifiers are the ones I use to connect to the Sharepoint portal.

Regards,
Mark

**Comment by fatfingers23** [comment]
Hello Mark,

If your password has ",',<,>,& in it then it will cause the error. There was a bug where the XML was not properly escaped when authenticating with Microsoft. You could try your lucky with [#pr52](https://github.com/jasonrollins/shareplum/pull/52) and see if that helps. It fixes the bug and has better error handling to tell you what is more likely your error. Hope this helps!

**Comment by jasonrollins** [comment]
Did this resolve your issue?

**Comment by Mark531** [comment]
In the end, I used another library. I can't afford using a patched library on a production code.

**Comment by jasonrollins** [comment]
Which library are you using?

**Comment by Mark531** [comment]
We're using PySmbClient.

**Comment by jasonrollins** [comment]
Thanks for the info.

**Comment by jasonrollins** [comment]
I believe this is now fixed in v0.4.2.
