### ISSUE TITLE
Unable to add date columns to SharePoint list

### ISSUE THREAD

**Issue by auanish** [jasonrollins/shareplum#65]
The following code works for me when my CSV doesn't have any date columns. When I include a date column, the code still runs but no data is loaded onto the SP list.

```
from shareplum import Site
from requests_ntlm import HttpNtlmAuth
import csv

cred = HttpNtlmAuth(username, password)
site = Site('https://sharepoint', auth=cred)
my_db = site.List('MY_DB')

with open('filename.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    my_data = [dict(d) for d in reader]

rca_db.UpdateListItems(data=my_data, kind='New')
print('done')
```

**Comment by jasonrollins** [comment]
You have to have the correct format for you dates or SharePoint will reject
them.  You should convert to the python datetime to do this for you.

**Comment by jasonrollins** [comment]
I'm closing this issue.  Please reopen it if your issue isn't resolved.
