### ISSUE TITLE
sp_list.GetListItems() returning list of dictionaries

### ISSUE THREAD

**Issue by jarichardsonccbf** [jasonrollins/shareplum#70]
Is this correct? Each line of data is stored as a dictionary. Was expecting a dataframe or similar such object to return.

<img width="597" alt="dictlist" src="https://user-images.githubusercontent.com/47988509/74962508-0fbb4e00-53de-11ea-9a8f-e06eda4bc035.PNG">

**Comment by jarichardsonccbf** [comment]
pd.DataFrame(thelistofdictionaries)

**Comment by jasonrollins** [comment]
Did you have some recommendation instead of a list of dictionaries?
