### ISSUE TITLE
Error while using query to filter fields

### ISSUE THREAD

**Issue by F2BA** [jasonrollins/shareplum#71]
While reading data from a list, the query is not working. If I use "fields" it works, but if I use the "quer", I get an error

 fields = ['Arquivo','JSON','Área','Subárea']
 query = {'Where': [('Eq', 'Arquivo', file_type)]}

  sp_list = site.List('Tipos de Arquivo')
  data = sp_list.GetListItems(fields=fields) #IT WORKS
  data = sp_list.GetListItems(query=query) # IT DOESN'T WORK
----------------------------------------------
printing data gives the error below if I query it:
data  <Response [500]>

**Comment by jasonrollins** [comment]
Check it now.  I think a pushed a broken version on to pypi late last week.

**Comment by F2BA** [comment]
Thanks
