### ISSUE TITLE
Updating List Items on O365 Site

### ISSUE THREAD

**Issue by dgutman** [jasonrollins/shareplum#72]
I can't tell if it's possible to update a list using shareplum on an office 365 site.  I've done this before using an onpremise sharepoint installation, but we have recently moved to Office365, which has been... "fun".

I am getting a 500 error when I try:

sp_list.update_list_items(data=dataUpdates,kind='Update')

Oddly, I can connect to the site, get the list items,for example 

   li = sp_list.GetListItems()

worked fine.   But I am getting some futureWarning issues suggesting I am using the SOAP api to connect.  It would be odd if only part of the SOAP api wasn't working, but who knows...

shareplumDev\soap.py:50: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if self.batch:

Is there any way to at least use the cookies and AUTH I already have, and build my own POST requests to the REST API?  I imagine all of this is under active development as the REST API seems to have been updated in the last week..

**Comment by jasonrollins** [comment]
Check it now.  I think a pushed a broken version on to pypi late last week.
