### ISSUE TITLE
File Upload in a document Library

### ISSUE THREAD

**Issue by AshirwadSatapathi** [jasonrollins/shareplum#76]
Hello there,

I have gone through the documentation but i'm unable to find a snippet to help me upload a file in a document Library. I'm trying upload a pdf document to the document library of one of my subsite.

Kindly help me out with this issue.

Thanks and Regards
Ashirwad Satapathi

**Comment by isaacnorman82** [comment]
If you have something like https://<your_tenant>.sharepoint.com/sites/<sitename>/Shared Folder/my folder
Then you need to create a Site object with host=https://<your_tenant>.sharepoint.com, site=sites/<sitename>/ and then from the site object create a Folder with site.Folder("Shared Folder/my folder") then call .upload_file().

**Comment by AshirwadSatapathi** [comment]
Hi Isaac, Let's assume i have a Sub Site and there is Document Library inside which i have a Folder. Can i upload the file there? It's a Pdf File. I Need to save some information related to the file in it, that's why i'm using a document library. Any help would be appreciated.

**Comment by AshirwadSatapathi** [comment]
> If you have something like https://<your_tenant>.sharepoint.com/sites//Shared Folder/my folder
> Then you need to create a Site object with host=https://<your_tenant>.sharepoint.com, site=sites// and then from the site object create a Folder with site.Folder("Shared Folder/my folder") then call .upload_file().

Hi Isaac, Let's assume i have a Sub Site and there is Document Library inside which i have a Folder. Can i upload the file there? It's a Pdf File. I Need to save some information related to the file in it, that's why i'm using a document library. Any help would be appreciated.

**Comment by luihzpg** [comment]
Hello I can successfully Create, Read and Delete files. However, when I upload files through folder.upload_file('content','filepath').

The file is actually uploaded but it gets corrupted. I guess it is because of the "content" that the function folder.upload adds to the file once it is uploaded to my sharepoint folder.

How can I circumvent this problem, the ONLY type of file that doesn't get corrupted is a TXT file. Other files either EXCEL, POWERPOINT or PDFs all get corrupted once they get uploaded to sharepoint with function folder.upload_file.

Many thanks

**Comment by isaacnorman82** [comment]
I suspect you're opening those files in the wrong mode, you need "rb".  I've used shareplum to upload binary files no problem.

**Comment by luihzpg** [comment]
Many thanks Isaac for your answer.

So how should I phrase the command to satisfy the correct mode "rb"?

I am trying to upload a Power Point Presentation as follows and added the "rb" right before the file name as rb'presentation.pptx as follows:

folder = site.Folder('Documentos Compartilhados/Apresentações Workshop')
folder.upload_file('hello',**rb**'presentation.pptx')
folder.get_file('presentation.pptx')
folder.check_out('presentation.pptx')
folder.check_in('presentation.pptx', "My check-in comment")


When I try to open this file from sharepoint it says it is a corrupted file.

However if I tried to add a "txt" file it would work. 

I think that there might be a problem in the command folder.upload( ).

I guess it corrupts the file when you add the content to the file.

Thanks alot!

**Comment by isaacnorman82** [comment]
If you look at the code for upload file it's just expecting the argument 'contents' to be the data.  You need to use the python file open() command with mode set to binary then read the whole file into a variable.  Google reading a binary file in python.

**Comment by luihzpg** [comment]
Dear Isaac, 
Many thanks for your help. It indeed work!

All I had to do was:

```
> with open(fileName, mode='rb') as file: # b is important -> binary
>     fileContent = file.read()
```

and only after that include "fileContent" at folder.upload_file(fileContent, presentation.pptx)

Tks a lot!

**Comment by jasonrollins** [comment]
What should I do to make this more clear?  Do you think I just need to put up an example with a binary file or is there some better way to convey how to upload binary data?

**Comment by isaacnorman82** [comment]
Do you have any tests?  You could create some high level pytests that need a username and password and URL.  Cover all the basic usage and prove everything works.

**Comment by jasonrollins** [comment]
I have some tests!  They are "unittests" in the shareplum/tests/ folder.
You do have to edit test_server.json for your test site and export
TEST_PASSWORD=*****.  Then you can run "python -m unittest".  I'm not very
experienced with python testing so I'm not aware of pytest.

**Comment by AshirwadSatapathi** [comment]
Hi @jasonrollins  

Is it possible to upload the file in a document library. I'm relatively new to sharepoint. It's an major requirement for me. Is there any way in which i can upload a file directly to a document library.

Please let me know.

There is one more thing, when i create a folder, what does shared folder refer to? Is there a predefined shared folder in sharepoint where it'll create a new folder.

Looking forward to hearing from you.

Thanks in advance.

**Comment by jasonrollins** [comment]
I've updated the docs to show how to upload files.

Check it out:
https://shareplum.readthedocs.io/en/latest/files.html#id1
