### ISSUE TITLE
There's not way to determine the success or failure of many public functions

### ISSUE THREAD

**Issue by isaacnorman82** [jasonrollins/shareplum#77]
For instance in Folder, we have functions like upload_file that return nothing and others that explicitly return None.  There should be a standard way across the library to return a status.  I would recommend for a light touch just doing a response.raise_for_status or returning response.ok.

**Comment by jasonrollins** [comment]
Thanks that's great feedback.  I've added a response.raise_for_status to all of the methods.

**Comment by isaacnorman82** [comment]
Hi, I've just taken a look at what you did and I don't think raise_for_status works like you think

What you've got is something like:
```
if response.status != 200:
  response.raise_for_status()
  <log error>

```
The log error line here will never be hit.  Raise for status raises and exception if status is not OK.

If you want to do raise_for_status I would do something like:

```
response = self._session.get(...)
response.raise_for_status()  # will throw and exception if not ok
```

Alternatively you could have a shareplum/exceptions.py

```
def ShareplumError(Exception):
  def __init__(self, msg, details=None):
        if details:
            super().__init__(f"{msg} : {details}")
        else:
            super().__init__(msg)

def check_response(response):
  try:
    response.raise_for_status()
  except Exception as err:
    raise ShareplumException(<high level text saying a request failed, maybe include response.url>, err)
```

Your code would then be something like
```

from exceptions import check_response
def do_something(self):
  response = self.session.get(...)
  check_response(response)

```

You could go further and have more specific exceptions:
ShareplumError(Exception)
--ShareplumAuthError(ShareplumError)
--ShareplumConnectionError(ShareplumError)
etc...

That would allow users of your library to just catch the top level one when making calls to your library.

**Comment by jasonrollins** [comment]
Is this incorporated in your latest pull request or should we leave it open to address the other SharePlum exceptions you have suggested?

**Comment by isaacnorman82** [comment]
I think we can close this now.
