### ISSUE TITLE
Unhelpful exception when creating a site with a bad url

### ISSUE THREAD

**Issue by isaacnorman82** [jasonrollins/shareplum#78]
If you try and create a site with an invalid site URL you'll trigger an exception when GetUsers is called:

E           requests.exceptions.ConnectionError: GetUsers GetListItems request failed - status code: 404

env\lib\site-packages\shareplum\site.py:252: ConnectionError

I think the code needs to detect failure to create a site prior to this and raise an exception to the caller, or at least catch this exception and raise something less misleading.

**Comment by jasonrollins** [comment]
I've updated the code to include a get_site function during init of the site object.  It uses the response.raise_for_status() to return and error. Example:
`HTTPError: 500 Server Error: Internal Server Error for url: https://jrollins.sharepoint.com/sites/TestSit/_vti_bin/Sites.asmx`

**Comment by isaacnorman82** [comment]
You've closed two issues I raised, have you published a new version?

**Comment by jasonrollins** [comment]
Sorry.  I have incorporated your issues into the current git master.
