### ISSUE TITLE
400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by ram4031** [jasonrollins/shareplum#80]
when i try to upload csv to folder i get below error 

`{
  "errorMessage": "400 Client Error: Bad Request for url: https://mycompany.sharepoint.com/sites/ZoomReports/_api/web/GetFolderByServerRelativeUrl('Shared%20Documents/Hult%20Campus%20Boston/2020-04-15')/Files/add(url='Michael%20McCarthy's%20Personal%20Meeting%20Room%202020-04-15%2004-37%203.csv',overwrite=true)",
  "errorType": "HTTPError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 203, in savetoSharepoint\n    _folder.upload_file(csv_binary, FILENAME)\n",
    "  File \"/var/task/shareplum/folder.py\", line 117, in upload_file\n    response.raise_for_status()\n",
    "  File \"/var/task/requests/models.py\", line 941, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"
  ]
}`

Can you please help

**Comment by jasonrollins** [comment]
Could you provide some sample code of what you are doing when you get the
error message?

**Comment by Tmagga** [comment]
Hi.
I am having, what looks like, the same issue. 
My script is checking file versions and downloading them just fine.
The issue occurs when trying to upload a file (it will be a new version of an existing file, so should be overwritten)
I'm passing the site after my login func. (Same as for downloading)

`def upload_smc(site,userdata_dict):
    folder=site.Folder(userdata_dict['fil_smc']['fil_url'])
    smc_file=userdata_dict['loc_path']+'\\'+userdata_dict['fil_smc']['filnavn']
    with open(smc_file,'rb') as file:
        file_content=file.read()
    folder.upload_file(file_content,userdata_dict['fil_smc']['filnavn'])
    print (f"Updated SMC file, {userdata_dict['fil_smc']['filnavn']} is uploaded to {folder.folder_name} ")`

Args= [site] is passed from login and works for download- same variable
         [userdata_dict] is a dict with from json with stored data. (userdata_dict['fil_smc']['filnavn']="BB_K3_02_Sammenstillingsmodell.smc")
(userdata_dict['fil_smc']['fil_url']="Delte dokumenter/Prosjekt K-TRE/07 - Detaljprosjekt/01 - BIM/02 IFC og SMC"

after running for a while i get the same error as the poster above
![image](https://user-images.githubusercontent.com/50455111/89190760-37742c00-d5a2-11ea-9751-eecc5cfe7e4b.png)
