### ISSUE TITLE
public api folder.get_file() removed since last pip release

### ISSUE THREAD

**Issue by isaacnorman82** [jasonrollins/shareplum#82]
Few issues in one here:

1) folder.get_file() has been removed and replaced with read_txt_file and download_file.  This will break user code when they upgrade, I'd recommend not changing or removing public apis if possible.  At least leave the old function in place and raise an exception with text '<func name> no longer supported, please use <new func name> instead'.

2) The old get_file() doesn't work for non-text files as it returns response.text.  I guess this might be why it's now called read_txt_file.  Instead, why not just return response.content.  Then it works for all files.  

I would simply revert to get_file and remove read_txt_file and download_file.  You can add an optional argument file_name=None to get_file.  If not None, write to file, if None, return content.    Personally I wouldn't bother, writing content to a file is trivial in python and I'd leave that to the user, shareplum should just be offering a way to interact with sharepoint.

3) I wanted to title this issue 'since release 0.4.4' but if I look at github that isn't in releases.  The releases in github don't match to that in pip, making tracking issues difficult.

**Comment by jasonrollins** [comment]
1. Yes sorry about that.  I was hoping I could make the change fast enough to not impact too many people.
2. I think that's a good change.
3. I'm not sure what you mean by this.  I do try to tag the versions in my GitHub.  Maybe I'm not familiar enough with GitHub to do this correctly.

**Comment by isaacnorman82** [comment]
re point 3.  If you click on the releases tab (code then releases in github) you'll see you've made one release v0.1.1.  There's a tags section, that has the versions as seen by pip.  So I guess for it to be obvious to people you want to do whatever you did for v0.1.1 for all your other tags when you make them in future.  

Here's a how to: https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

To be honest it's not that important, it's just a bit confusing to know i have 0.4 something, go to your releases and only see 0.1.1.

**Comment by jasonrollins** [comment]
Thanks.  I went ahead and published the release for 0.4.5.  I can go back and do the same for some of the other releases if you think that's a good idea.

**Comment by isaacnorman82** [comment]
Probably not important thanks.

**Comment by azharmajeed** [comment]
Hi,

I am trying to do something similar, like trying to download a xlsx file in a sharepoint folder. When I run this code
```
authcookie = Office365(spDomain, username='******', password='*****').GetCookies()
site = Site(spsite, Version.v2016, authcookie=authcookie)
folder = site.Folder('Shared Documents/General/Sub Folder/')
```

I get the error saying -
```
AttributeError: 'Site' object has no attribute 'Folder'
```

I dont get what I am doing wrong. I am using version "0.5.1". Could you please help me figure out the issue or find a work around to download a file. Appreciate any help.
