### ISSUE TITLE
Improve unittests

### ISSUE THREAD

**Issue by isaacnorman82** [jasonrollins/shareplum#87]
I've just tried running the tests and have some suggested improvements:

Test settings is a tracked file and so anyone aside from you has to edit it and then will run into issues because git is seeing changes to a file, but you'll never want to commit or merge them.  I'd make it untracked, or better yet:

Convert test_server.json to test_settings.py.  Then have this in your test file:

```
try:
    from tests.local_test_settings.py import test_settings
except ImportError
    from  tests.test_settings.py import test_settings
```

Your tests would then have:

`test_settings.username`

Second, in the instructions you gave me for running the tests you run from the tests directory.  This means that the tests can't import the source package, but instead use the installed package.  This means you need to install the package to test and can easily end up accidentally testing the code.

To fix this from the directory above tests and the package, you should run

```
python -m unittest discover  # all tests
python -m unittest tests.test_site # a test file
python -m unittest tests.test_site.test_function # a test function
```

You'll notice a lot of failures if you do this, because you have a relative open of 'test_server.json' which is no longer found.  My solution above solves this too by doing an import of tests.test_settings.  Note you'll probably need to add __init__.py to tests.

Next up, two of the tests fail.  One because of an exception after getting a response of 201.  201 is not an error code, but you're testing all errors as 200.  There's response.OK for this, but you don't want that anyway, you want to just do response.raise_for_status probably.

Other failure is about a call to /_api/web/roleassignments in test_site_roleassignments.  I don't know the cause of this, possibly site permissions?  I am an owner of the site I'm testing against though.

**Comment by isaacnorman82** [comment]
@jasonrollins any info on what causes roleassignments to fail?  Is there something in sharepoint I need permissions for?

**Comment by jasonrollins** [comment]
I'm not sure.  Maybe we should remove it from the unittests.  I'm not tied to it.  I just know what my personal O365 SharePoint site does.  I added it because it's a site function I could test.  I'm not sure if all users can execute it.

**Comment by isaacnorman82** [comment]
I'm not sure what's best, may as well leave it in for now.  I did a bit of googling and can't find what permission is needed.
