### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by esztermarton** [jasonrollins/shareplum#90]
Hi! I installed shareplum with pip this morning (v 0.5.0) & am stuck with trying to get a file content.

Please see my code below:

```
# conn.login is an email, password is a password
# conn.host has following template: https://{organisation name}.sharepoint.com
auth_cookie = Office365(
    conn.host, username=conn.login, password=conn.password,
).GetCookies()

# conn.host has following template: https://{organisation name}.sharepoint.com
# conn.schema looks like this: sites/{group name}
site_url = f"{conn.host}/{conn.schema.strip('/')}"
site = Site(site_url, authcookie=auth_cookie, version=Version.v365)

folder = site.Folder("Shared Documents/MyFolder")
    for file in folder.files:
         content = folder.get_file(file)
```
On the line with content, an error is raised (I've changed the actual organisation name to ORG and the actualy group name to be GROUP):

```
File "/opt/miniconda3/envs/env_name/lib/python3.6/site-packages/shareplum/folder.py", line 154, in get_file
    response.raise_for_status()
  File "/opt/miniconda3/envs/env_name/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://{ORG}.sharepoint.com/sites/GROUP/_api/web/GetFileByServerRelativeUrl('/sites/GROUP/Shared%20Documents/ELR/%7B'odata.type':%20'SP.File',%20'odata.id':%20%22https://ORG.sharepoint.com/sites/GROUP/_api/Web/GetFileByServerRelativePath(decodedurl='/sites/GROUP/Shared%20Documents/ELR/something.txt')%22,%20'odata.editLink':%20%22Web/GetFileByServerRelativePath(decodedurl='/sites/GROUP/Shared%20Documents/ELR/something.txt')%22,%20'CheckInComment':%20'',%20'CheckOutType':%202,%20'ContentTag':%20'%7B46A7D76C-C8F0-4C70-9C8A-1B1E674D741A%7D,1,1',%20'CustomizedPageStatus':%200,%20'ETag':%20'%22%7B46A7D76C-C8F0-4C70-9C8A-1B1E674D741A%7D,1%22',%20'Exists':%20True,%20'IrmEnabled':%20False,%20'Length':%20'331',%20'Level':%201,%20'LinkingUri':%20None,%20'LinkingUrl':%20'',%20'MajorVersion':%201,%20'MinorVersion':%200,%20'Name':%20'something.txt',%20'ServerRelativeUrl':%20'/sites/GROUP/Shared%20Documents/ELR/something.txt',%20'TimeCreated':%20'2020-04-20T11:43:52Z',%20'TimeLastModified':%20'2020-04-20T11:43:52Z',%20'Title':%20None,%20'UIVersion':%20512,%20'UIVersionLabel':%20'1.0',%20'UniqueId':%20'46a7d76c-c8f0-4c70-9c8a-1b1e674d741a'%7D')/$value
```

Since the API is so _wonderfully_ simple, I can't really see where I'm going wrong - but equally perhaps I'm misusing it somehow with the site creation or something.  Or is this a bug? Thanks for your help!

**Comment by jasonrollins** [comment]
Is your site url and folder path correct?  Can you use the any of the LIST properties with that site url?

**Comment by esztermarton** [comment]
I just did all of these tutorial ones: https://shareplum.readthedocs.io/en/latest/tutorial.html, both with a new list and a list that already existed and it all works fine! 

I'm pretty sure the site URL and folder path are correct because I can list folders and files in my folder. I can also upload and delete. It is just the download that fails with the 404!

**Comment by jasonrollins** [comment]
Very strange.  Do you think it could be the folder path itself?  Does it
have a "\t" or "\n" character?  Can you try passing it like this r"My
Docs\Folder Path"?

**Comment by esztermarton** [comment]
It doesn't, the folder path is Shared Documents/ELR ---but I tried that anyway. And the file's called something.txt.

Could you maybe print out the URL for a working example and I can go and compare what my URL looks like? Or do you maybe have a public folder that you can download from that I can try too to see if its maybe some other settings I'm not considering?

**Comment by jasonrollins** [comment]
I unfortunately only have a personal SharePoint site with one user.  Here is an example that works on my Office365 site:
`from shareplum import Site
from shareplum import Office365
from shareplum.site import Version

url = "https://jrollins.sharepoint.com/sites/TestSite"

authcookie = Office365('https://jrollins.sharepoint.com', username='jrollins', password='hunter2').GetCookies()
site = Site(url, version=Version.v2013, authcookie=authcookie)

folder = site.Folder('Shared Documents/This Folder')
folder.upload_file('Hello', 'new.txt')
folder.get_file('new.txt')`

**Comment by esztermarton** [comment]
Yes, this also worked for me.

The bug was hidden in plain site. Sorry for taking your time with this, I was being silly. 

I assumed and didn't check, that folder.files returns filenames, like folder.folders. However folder.files returns a dict, so when i feed it to folder.get_file(file), naturally returned a 404!  🤦‍♀️

Thanks for your help!!

**Comment by jasonrollins** [comment]
Ah. That's in consistent. Sorry about that
