### ISSUE TITLE
make a release with new request handling

### ISSUE THREAD

**Issue by isaacnorman82** [jasonrollins/shareplum#92]
Can I have a release I can install from pip with the request response handling please?

**Comment by jasonrollins** [comment]
No problem, but I'll have to do it this evening

**Comment by isaacnorman82** [comment]
Thanks, I can get 0.5.1 from pip, but I don't see it in github as a release or tag?

**Comment by jasonrollins** [comment]
I forgot to tag it. I'll do that

**Comment by jasonrollins** [comment]
Done.
