### ISSUE TITLE
folder.get_file('source.txt', 'destination.txt') - 3 positional arguments

### ISSUE THREAD

**Issue by mgjspidey** [jasonrollins/shareplum#93]
The get_file() does not seem to accept a destination variable, only the source variable - the two positional arguments accepted appear to be the folder (self) and the source file only.

Am I missing something?

**Comment by jasonrollins** [comment]
Sorry.  It was like that on an old version.  I updated the docs to correctly reflect that you only provide the file name you are downloading.
